// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: field/field.proto

package field

import (
	pagination "github.com/DevisArya/learn-microservices-protorepo/pb/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_field_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_field_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Field) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetFieldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *pagination.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data          []*Field               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldsResponse) Reset() {
	*x = GetFieldsResponse{}
	mi := &file_field_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsResponse) ProtoMessage() {}

func (x *GetFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetFieldsResponse) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{2}
}

func (x *GetFieldsResponse) GetPagination() *pagination.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetFieldsResponse) GetData() []*Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldResponse) Reset() {
	*x = GetFieldResponse{}
	mi := &file_field_field_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldResponse) ProtoMessage() {}

func (x *GetFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldResponse.ProtoReflect.Descriptor instead.
func (*GetFieldResponse) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{3}
}

func (x *GetFieldResponse) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

type CreateFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFieldRequest) Reset() {
	*x = CreateFieldRequest{}
	mi := &file_field_field_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFieldRequest) ProtoMessage() {}

func (x *CreateFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFieldRequest.ProtoReflect.Descriptor instead.
func (*CreateFieldRequest) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFieldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFieldRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFieldRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFieldRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFieldResponse) Reset() {
	*x = CreateFieldResponse{}
	mi := &file_field_field_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFieldResponse) ProtoMessage() {}

func (x *CreateFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFieldResponse.ProtoReflect.Descriptor instead.
func (*CreateFieldResponse) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFieldResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateFieldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateFieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         *uint64                `protobuf:"varint,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFieldRequest) Reset() {
	*x = UpdateFieldRequest{}
	mi := &file_field_field_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFieldRequest) ProtoMessage() {}

func (x *UpdateFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFieldRequest.ProtoReflect.Descriptor instead.
func (*UpdateFieldRequest) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFieldRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFieldRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFieldRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateFieldRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateFieldRequest) GetPrice() uint64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_field_field_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_field_field_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_field_field_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_field_field_proto protoreflect.FileDescriptor

const file_field_field_proto_rawDesc = "" +
	"\n" +
	"\x11field/field.proto\x12\x05field\x1a\x1bpagination/pagination.proto\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"w\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\"m\n" +
	"\x11GetFieldsResponse\x126\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x16.pagination.PaginationR\n" +
	"pagination\x12 \n" +
	"\x04data\x18\x02 \x03(\v2\f.field.FieldR\x04data\"6\n" +
	"\x10GetFieldResponse\x12\"\n" +
	"\x05field\x18\x01 \x01(\v2\f.field.FieldR\x05field\"t\n" +
	"\x12CreateFieldRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\"?\n" +
	"\x13CreateFieldResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x12UpdateFieldRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x04H\x03R\x05price\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_price\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb5\x02\n" +
	"\fFieldService\x12=\n" +
	"\tGetFields\x12\x16.pagination.Pagination\x1a\x18.field.GetFieldsResponse\x12.\n" +
	"\bGetField\x12\t.field.Id\x1a\x17.field.GetFieldResponse\x12D\n" +
	"\vCreateField\x12\x19.field.CreateFieldRequest\x1a\x1a.field.CreateFieldResponse\x12?\n" +
	"\vUpdateField\x12\x19.field.UpdateFieldRequest\x1a\x15.field.StatusResponse\x12/\n" +
	"\vDeleteField\x12\t.field.Id\x1a\x15.field.StatusResponseB=Z;github.com/DevisArya/learn-microservices-protorepo/pb/fieldb\x06proto3"

var (
	file_field_field_proto_rawDescOnce sync.Once
	file_field_field_proto_rawDescData []byte
)

func file_field_field_proto_rawDescGZIP() []byte {
	file_field_field_proto_rawDescOnce.Do(func() {
		file_field_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_field_field_proto_rawDesc), len(file_field_field_proto_rawDesc)))
	})
	return file_field_field_proto_rawDescData
}

var file_field_field_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_field_field_proto_goTypes = []any{
	(*Id)(nil),                    // 0: field.Id
	(*Field)(nil),                 // 1: field.Field
	(*GetFieldsResponse)(nil),     // 2: field.GetFieldsResponse
	(*GetFieldResponse)(nil),      // 3: field.GetFieldResponse
	(*CreateFieldRequest)(nil),    // 4: field.CreateFieldRequest
	(*CreateFieldResponse)(nil),   // 5: field.CreateFieldResponse
	(*UpdateFieldRequest)(nil),    // 6: field.UpdateFieldRequest
	(*StatusResponse)(nil),        // 7: field.StatusResponse
	(*pagination.Pagination)(nil), // 8: pagination.Pagination
}
var file_field_field_proto_depIdxs = []int32{
	8, // 0: field.GetFieldsResponse.pagination:type_name -> pagination.Pagination
	1, // 1: field.GetFieldsResponse.data:type_name -> field.Field
	1, // 2: field.GetFieldResponse.field:type_name -> field.Field
	8, // 3: field.FieldService.GetFields:input_type -> pagination.Pagination
	0, // 4: field.FieldService.GetField:input_type -> field.Id
	4, // 5: field.FieldService.CreateField:input_type -> field.CreateFieldRequest
	6, // 6: field.FieldService.UpdateField:input_type -> field.UpdateFieldRequest
	0, // 7: field.FieldService.DeleteField:input_type -> field.Id
	2, // 8: field.FieldService.GetFields:output_type -> field.GetFieldsResponse
	3, // 9: field.FieldService.GetField:output_type -> field.GetFieldResponse
	5, // 10: field.FieldService.CreateField:output_type -> field.CreateFieldResponse
	7, // 11: field.FieldService.UpdateField:output_type -> field.StatusResponse
	7, // 12: field.FieldService.DeleteField:output_type -> field.StatusResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_field_field_proto_init() }
func file_field_field_proto_init() {
	if File_field_field_proto != nil {
		return
	}
	file_field_field_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_field_field_proto_rawDesc), len(file_field_field_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_field_field_proto_goTypes,
		DependencyIndexes: file_field_field_proto_depIdxs,
		MessageInfos:      file_field_field_proto_msgTypes,
	}.Build()
	File_field_field_proto = out.File
	file_field_field_proto_goTypes = nil
	file_field_field_proto_depIdxs = nil
}
